project_name: argocd-hydrate
git:
  ignore_tags: true
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/kazysgurskas/argocd-hydrate/internal/cmd.getVersion.Version={{.Env.VERSION}}
      - -X github.com/kazysgurskas/argocd-hydrate/internal/cmd.getVersion.GitCommit={{.Env.GIT_COMMIT}}
      - -X github.com/kazysgurskas/argocd-hydrate/internal/cmd.getVersion.BuildDate={{.Env.BUILD_DATE}}
    main: ./cmd/argocd-hydrate/main.go

dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/argocd-hydrate:{{ .Env.VERSION }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/argocd-hydrate:latest"
    build_flag_templates:
      - "--build-arg=VERSION={{.Env.VERSION}}"
      - "--build-arg=GIT_COMMIT={{.Env.GIT_COMMIT}}"
      - "--build-arg=BUILD_DATE={{.Env.BUILD_DATE}}"
    dockerfile: Dockerfile

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
