project_name: argocd-hydrate

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/kazysgurskas/argocd-hydrate/internal/cmd.getVersion.Version={{.Env.VERSION}}
      - -X github.com/kazysgurskas/argocd-hydrate/internal/cmd.getVersion.GitCommit={{.Env.GIT_COMMIT}}
      - -X github.com/kazysgurskas/argocd-hydrate/internal/cmd.getVersion.BuildDate={{.Env.BUILD_DATE}}
    main: ./cmd/argocd-hydrate/main.go

dockers:
  - id: fireactions-amd64
    use: buildx
    extra_files:
      - "./"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
    goarch: amd64
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/argocd-hydrate:{{ .Env.VERSION }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/argocd-hydrate:latest"
    dockerfile: Dockerfile
  - id: argocd-hydrate-arm64
    use: buildx
    extra_files:
      - "./"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
    goarch: amd64
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/argocd-hydrate:{{ .Env.VERSION }}-arm64"
    dockerfile: Dockerfile

archives:
   - format: tar.gz
     name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
